name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current tag
        id: current-tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "current-tag=${TAG}" >> $GITHUB_ENV

      - name: Calculate new tag
        id: new-tag
        run: |
          CURRENT_TAG=${{ env.current-tag }}
          if [ -z "$CURRENT_TAG" ]; then
            NEW_TAG="v1.0.0"
          else
            TAG_NAME=$(echo $CURRENT_TAG | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1/')
            TAG_VERSION=$(echo $CURRENT_TAG | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\2.\3/')
            MAJOR=$(echo $TAG_VERSION | cut -d. -f1)
            MINOR=$(echo $TAG_VERSION | cut -d. -f2)
            NEW_MINOR=$((MINOR + 1))
            NEW_TAG="v${TAG_NAME}.${MAJOR}.${NEW_MINOR}"
          fi
          echo "new-tag=${NEW_TAG}" >> $GITHUB_ENV

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.new-tag }}
          git push origin ${{ env.new-tag }}
