name: Auto Release

on:
  push:
    branches:
      - main  # або інша гілка, на якій ви хочете запускати цей процес

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            echo "No tags found, setting latest_tag to 1.2.1.0"
            latest_tag="1.2.1.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      
      

      - name: Increment version
        id: increment_version
        run: |
          version="${{ env.latest_tag }}"
          if [ -z "$version" ]; then
            version="1.2.0.1"
          fi
          IFS='.' read -r -a version_parts <<< "$version"
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.$((${version_parts[3]} + 1))"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config user.name "gogolevjuri"
          git config user.email "gogolevjuri@gmail.com"
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'

      - name: mod name
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          MOD=mod.wotStat_$VERSION.wotmod
          echo Version: $VERSION
          echo Mod name: $MOD
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MOD=$MOD" >> $GITHUB_ENV

      - name: Set execute permission for build.sh
        run: chmod +x WOTSTAT/build.sh
        shell: bash

      - name: Set execute permission for WOTSTAT
        run: chmod 777 -R WOTSTAT
        shell: bash

      - name: build
        run: cd WOTSTAT && ./build.sh -v $VERSION && echo Mod name $MOD
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MOD }}
          path: WOTSTAT/${{ env.MOD }}

      - name: upload linux artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.new_version }}
          release_name: ${{ env.new_version }}
          draft: false
          prerelease: false
          files: WOTSTAT/${{ env.MOD }}
          token: ${{ github.token }}
          body: |


            ----------------------
            `canary_upgrade=0.0`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


